# Redis数据库索引（默认为0）
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    password: Fnd123456
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0


# 此为示例，非真实
wechatmp:
  appId: wx023c80169b061dbb #公众号AppID
  secret: af33823c6e699354eaf52ad604d4dea9 #公众平台配置的APPSecret 如：32d4734ad70ce3a4ab964249764cba3a
  token: abcdqwer #公众平台配置的Token
  encodingAESKey: 1qTestazxcvfr45tgb #公众平台配置的EncodingAESKey

